<details class="journal-inserts"><summary>Tambahkan komponen artikel</summary>
    @if($mediaChoices->isNotEmpty())
        <label for="editor-media">Gambar dari media artikel</label><select id="editor-media"><option value="">Pilih media</option>@foreach($mediaChoices as $media)<option value="{{ $media->id }}">{{ $media->alt ?: 'Media '.$media->id }}</option>@endforeach</select><button type="button" data-block-insert="media">Tambahkan gambar</button>
        <fieldset data-repeat="gallery" data-limit="8"><legend>Galeri (2–8 gambar, sesuai urutan)</legend><div data-repeat-rows></div><template><div data-repeat-row><label>Gambar<select data-field=""><option value="">Pilih media</option>@foreach($mediaChoices as $media)<option value="{{ $media->id }}">{{ $media->alt ?: 'Media '.$media->id }}</option>@endforeach</select></label>@include('admin.blog-posts._row-actions')</div></template><button type="button" data-repeat-add>Tambah gambar galeri</button></fieldset><button type="button" data-block-insert="gallery">Tambahkan galeri ke isi</button>
    @else<p>Simpan draft, lalu upload media di bagian Media untuk menambahkan gambar/galeri milik artikel.</p>@endif
    <label for="editor-callout-title">Judul callout</label><input id="editor-callout-title" maxlength="200"><label for="editor-callout-text">Isi callout</label><textarea id="editor-callout-text" maxlength="2000" rows="3"></textarea><label for="editor-callout-type">Jenis callout</label><select id="editor-callout-type"><option value="note">Catatan</option><option value="tip">Tips</option><option value="warning">Perhatian</option></select><button type="button" data-block-insert="callout">Tambahkan callout</button>
    <label for="editor-cta-label">Teks tombol CTA</label><input id="editor-cta-label" maxlength="200"><label for="editor-cta-url">Tujuan CTA (HTTPS atau path website)</label><input id="editor-cta-url" maxlength="2048" placeholder="/products"><button type="button" data-block-insert="cta">Tambahkan CTA</button>
    <label for="editor-youtube">ID atau URL video YouTube</label><input id="editor-youtube" placeholder="https://www.youtube.com/watch?v=…"><p>Hanya video YouTube. Kode iframe/script bebas tidak diterima.</p><button type="button" data-block-insert="youtube">Tambahkan video</button>
    <label for="editor-article">Artikel terkait dalam isi</label><select id="editor-article"><option value="">Pilih artikel</option>@foreach($articleChoices as $choice)<option value="{{ $choice->id }}">{{ $choice->title }}</option>@endforeach</select><button type="button" data-block-insert="article">Tambahkan artikel terkait</button>
</details>
